name: Python tests

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: |
          python3 fake_tnsping_responder.py &
          pytest --cov

      - uses: codecov/codecov-action@v3
